# Generated by Django 4.0.5 on 2022-06-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=True),
        ),
    ]
